azuhoverstats_currenthealth: Vida atual
azuhoverstats_initialhealth: Vida inicial
azuhoverstats_tooltierrequired: Nível de ferramenta obrigatório
azuhoverstats_fullness: completo
azuhoverstats_timeelapsed: Tempo decorrido
azuhoverstats_isready: está pronto! Atualizando o valor...
azuhoverstats_approximatenext: Próximo
azuhoverstats_timeuntilfinished: Tempo até terminar
azuhoverstats_burnsin: Queima em
azuhoverstats_timeuntilfull: Tempo até completar
azuhoverstats_itemtype: Tipo de item
azuhoverstats_itemtooltier: Nível do item